# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_sessiontoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
