# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0007_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
